### ISSUE TITLE
Copy image does not work

### ISSUE THREAD

**Issue by artofwalls** [Jon-Salmon/View-Image-Resurrected#2]
Here is another issue. When I click "Copy image" in the pull down menu, no image data is copied to the clipboard.
If I try to paste the image into a newly created document in Photoshop, the paste command simply doesn't work (this indicates no image data in the clipboard)

If I try to paste the image in Telegram for Desktop in order to send it in a chat, instead of the image I get this text: "Resultado de imagen de jessica alba deep cleavage". This is an example. It changes depending on the search made, obviously.

**Comment by Jon-Salmon** [comment]
Can you please try pasting into word and see if that works. If this issue is what i think it is, the javascript copy function isn't making a proper copy of the image, so the results are program dependent. I should be able to use a different method to get this to work, however this will limit compatibility to firefox 57 and higher

**Comment by Jon-Salmon** [comment]
I think this is fixed now, I've had to limit the feature to only supporting png and jpeg images unfortunately as well as firefox 57 as a minimum version.

**Comment by artofwalls** [comment]
It is a pity this feature doesn't work for Firefox pre-Quantum. I am one of the many that still have Firefox 56.0.2 because of many useful Add-ons that can't work in Quantum (Session Admin, Save Images, Show-me-more, Image Toolbar...).

Fortunately, the "Image Toolbar" add on (https://github.com/benbasson/imagetoolbar/) has the feature of copying the image and works in pre-Quantum Firefox so I can use this instead.
I'm glad the other features of your add on work correctly in both Quantum and pre-Quantum Firefox.

But this brings me another question: Since the Add on "Image Toolbar" can copy images, Couldn't it be possible to use a part of the code that runs only in Pre-Quantum instead of the current code for copying the image? I don't know, maybe what I'm asking is not possible because this would mead inserting some old style add on code into a Quantum certified Add on.

**Comment by artofwalls** [comment]
Forgot to mention. Pasting the image copied works correctly in Microsoft Word using Firefox 56.0.2, as you predicted. But apparently only in Microsoft Word. In any other program it just pastes a text if the program admits it (Corel Draw, Telegram, etc) or just nothing if the program admits image data but not text (Photoshop)

**Comment by Jon-Salmon** [comment]
I'm afraid that "Image Toolbar" uses methods that are only allowed in the old addon system that's been discontinued with firefox quantum, and thus can't be used here.
