### ISSUE TITLE
It works in Firefox pre-Quantum but addons.mozilla.org doesn't allow to install it

### ISSUE THREAD

**Issue by artofwalls** [Jon-Salmon/View-Image-Resurrected#3]
I know the copy image feature doesn't work in pre-Quantum Firefox but all other features work correctly. I know because as you know, I installed the Add on before you corrected the copy image feature and it is still installed (but not updated, since I have version 1.7.1 but addons.mozilla.org shows version 1.8.1).
So I suppose all that I wrote in the other Issue about all other features still working in pre-Quantum was because I was not using the updated version (and update from the add on admin does not update it).

I guess if I uninstall my version 1.7.1 and then try to install the add on again from addons.mozilla.org, it would not be possible anymore.

So I really don't know if all other features will still really work in pre-Quantum if I could manage to hack-update to 1.8.1 somehow. If so, it would be nice to mark it as compatible with pre-Quantum even if one of the features does not work so anybody pre-Quantum who hasn't already installed it before, can still install and update it.

I don't really know how the compatibility check in addons.mozilla.org goes. If it is the author who marks the versions that are compatible or is mozilla who determines it.

**Comment by Jon-Salmon** [comment]
I put that version out last night as the copy feature was broken (thanks for raising), and if i'd alowd versions pre to 57 to install and they tried to copy the addon would have crahsed. I'm currently just in the process of putting a new version together that checks what version of FF is installed and from that enables/disables to copy feature as required. It should be published shortly, but thanks for your very prompt feedback!

**Comment by Jon-Salmon** [comment]
Should be updated on AMO within a few hours
