### ISSUE TITLE
View image in new tab not working

### ISSUE THREAD

**Issue by SebaK666** [Jon-Salmon/View-Image-Resurrected#4]
Option "View Image' opens in new tab" not working on Firefox ESR 52.6.0. I use Tab Mix Plus. All links from bookmarks, address bar, search bar, history opens in new tab. But from View Image Resurrected
not

**Comment by Jon-Salmon** [comment]
In your tabmixplus config, do you have "Open links with a target attribute in current tab" selected.

![image](https://user-images.githubusercontent.com/26483285/36647028-572be396-1a77-11e8-9bc4-76d56d12ce75.png)

If you do this will be why as View Image Resurrected opens images in a current tab using the target="_blank" attribute, as not break user preferancees set elsewhere in the browser.

**Comment by SebaK666** [comment]
Yes, i  uncheck "Open links with target to existing frame in the current tab" and now working. But now I expect problems on other sites when additional pages open in background. But he has no choice. Thx

**Comment by Jon-Salmon** [comment]
A work around for this would be if you leave it checked in the tab mix plus options, then hold the 'ctrl' key when clicking on the link on google images. This should open the image in a new tab in the background for you.

**Comment by SebaK666** [comment]
It works. This solution is much better for me.  Many thanks.

**Comment by Jon-Salmon** [comment]
Glad to be of help.

**Comment by SebaK666** [comment]
Possible is always changelog on Mozilla addons site?

**Comment by Jon-Salmon** [comment]
Sorry, I don't quite understand what your asking?

**Comment by SebaK666** [comment]
On: https://addons.mozilla.org/firefox/addon/view-image-resurrected/versions/
Some versions they are without changelog 1.9.1,  1,8,2,  1.7.1 etc.
