### ISSUE TITLE
View Image and Options doesn't work anymore on Google.fr

### ISSUE THREAD

**Issue by zaykho** [Jon-Salmon/View-Image-Resurrected#6]
For some reasons, since yesterday, the addon doesn't work anymore on google.fr (no buttons displayed), If I force google to let me use google.com ( need 2 step : use google.com url and then click use "google.com" to stop google to redirect me to google.fr (steps needed everytime)), then those buttons are visible on google.com, obliviously, just using google.com is not an option with those steps needed everytime.

And since yesterday I didn't do any update or change to Firefox (auto update is set to off on everything), so, any idea why this doesn't work anymore on google.fr ?

EDIT: ok, looking at the inspector mode of both page ( google.fr and google.com ), it's seems that google.fr use this now:

`<table class="iAcjwd irc_but_r" summary="">`

 instead of : 

`<table class="_FKw irc_but_r" summary="">`

---

So i guess we should need to make the selector more robust here ?

https://github.com/Jon-Salmon/View-Image-Resurrected/blob/746d87e1711cdb0ba4c54be2a9a2b088d4d5a9e9/app/js/content-script.js#L64

This seems to work fine : 
`var pages = document.body.querySelectorAll("table.irc_but_r tbody tr"); `

**Comment by Jon-Salmon** [comment]
Thankyou for raising this, I think it's more wide spread than just google.fr as can reproduce on google.co.uk Have issued a fix to AMO removing the unnecessary class causing the issues. It's quite hard to work out googles class naming convention!

**Comment by Jon-Salmon** [comment]
Fix is in store
