### ISSUE TITLE
Issue about the size of the buttons

### ISSUE THREAD

**Issue by zaykho** [Jon-Salmon/View-Image-Resurrected#7]
Sorry to create an another issue. : c

So the latest fix about the remove of "execss class" did work, buttons are back, but now the issue is that  google did also changed the class name for the span : 

From
`<span class="_RKw _wtf _Rtf">`
to
`<span class="RL3J9c Cws1Yc uxaYBf">`

And because of this, the style of the buttons is not applied properly.

> google.co.uk
![google co uk](https://user-images.githubusercontent.com/6943022/37249978-5b45ea8c-24f2-11e8-9d96-ced1d2f5708f.png)

> google.com
![google com](https://user-images.githubusercontent.com/6943022/37249980-60fb53ae-24f2-11e8-9442-54c9a1e3a965.png)

It would maybe be better to keep those settings in the css file of the addon (with a dedicated class name) :

```
fill: currentColor;
height: 14px;
line-height: 14px;
width: 14px;
```

**Comment by Jon-Salmon** [comment]
I've been unable to reproduce, however i agree that using a custom class will be a more robust solution. I've added the css for both the span and the SVG within it.

**Comment by Jon-Salmon** [comment]
I've released a new version, let me know if this fixes it

**Comment by zaykho** [comment]
Thank you, it work well right now, perfect ! 

Issue fixed !
